spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/devdogs
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
