spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devdogs?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: user1
    password: test123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        show_sql: true
        format_sql=: true
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  error:
    #오류 응답에 exception의 내용을 포함할지 여부
    include-exception: true
    #오류 응답에 stacktrace 내용을 포함할지 여부 (ALWAYS, NEVER, ON_TRACE_PARAM)
    include-stacktrace: always
    whitelabel:
      #브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부
      enabled: false

thymeleaf:
  check-template-location: true
  cache: false

mvc:
  static-path-pattern: "/static/**"
config:
  activate:
    on-profile: dev